Tests/markov tests
piotrowskv/music_generation pull request #34
Opened 2023-01-01 18:27 UTC by piotrowskv

Added Markov Chain tests

2023-01-01 19:37 UTC, shilangyu requested changes

2023-01-01 19:37 UTC, shilangyu commented on models/models/markov_chain/markov_chain.py
> +    def prepare_data(self, midi_file):
Looks like merge conflicts incorrectly resolved

2023-01-01 21:13 UTC, piotrowskv commented on models/models/markov_chain/markov_chain.py
> +    def prepare_data(self, midi_file):
Corrected, thanks

2023-01-02 05:34 UTC, shilangyu commented on models/models/markov_chain/markov_chain.py
> +    def create_dataset(self, dataset):
pls bring back types

2023-01-02 14:08 UTC, shilangyu approved these changes

2023-01-03 01:46 UTC, szgorski approved these changes

2023-01-03 09:11 UTC, merged